#! /bin/bash -eu

aws dynamodb create-table \
    --attribute-definitions AttributeName=projectName,AttributeType=S AttributeName=projectType,AttributeType=S \
    --table-name Project_yutingli \
    --key-schema AttributeName=projectName,KeyType=HASH AttributeName=projectType,KeyType=RANGE \
    --billing-mode PAY_PER_REQUEST \
    --profile aws-training-profile \
    --region ap-southeast-1

# Output
# {
#      "TableDescription": {
#          "AttributeDefinitions": [
#              {
#                  "AttributeName": "projectName",
#                  "AttributeType": "S"
#              },
#              {
#                  "AttributeName": "projectType",
#                  "AttributeType": "S"
#              }
#          ],
#          "TableName": "Project_yutingli",
#          "KeySchema": [
#              {
#                  "AttributeName": "projectName",
#                  "KeyType": "HASH"
#              },
#              {
#                  "AttributeName": "projectType",
#                  "KeyType": "RANGE"
#              }
#          ],
#          "TableStatus": "CREATING",
#          "CreationDateTime": 1590840044.452,
#          "ProvisionedThroughput": {
#              "NumberOfDecreasesToday": 0,
#              "ReadCapacityUnits": 0,
#              "WriteCapacityUnits": 0
#          },
#          "TableSizeBytes": 0,
#          "ItemCount": 0,
#          "TableArn": "arn:aws:dynamodb:ap-southeast-1:494526681395:table/Project_yutingli",
#          "TableId": "97687523-990c-4ccd-9fc4-d37d4844f425",
#          "BillingModeSummary": {
#              "BillingMode": "PAY_PER_REQUEST"
#          }
#      }
#  }
