#! /bin/bash -eu

aws dynamodb query \
    --table-name Project_yutingli \
    --index-name memberName-index \
    --key-condition-expression 'memberName = :name' \
    --expression-attribute-values '{
                                        ":name": {"S": "yuting"}
                                    }' \
    --profile aws-training-profile \
    --region ap-southeast-1
